from backend.db.supabase import get_supabase_admin

questions = [
    {
        "domain": "sat_math",
        "topic": "Problem-Solving and Data Analysis",
        "skill": "Percentages",
        "difficulty": "easy",
        "prompt": "A store decreases the price of a jacket from $80 to $68. By what percent did the price decrease?",
        "choices": {"A": "12%", "B": "15%", "C": "17%", "D": "20%"},
        "correct_answer": "B",
        "explanation": "The decrease is 12 dollars. Divide the decrease by the original price: 12/80 = 0.15, or 15%.",
        "solution_steps": ["Find the change: 80 - 68 = 12.", "Use percent decrease = change / original.", "Compute 12 / 80 = 0.15.", "Convert to a percent: 15%."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_math",
        "topic": "Geometry",
        "skill": "Similar triangles",
        "difficulty": "medium",
        "prompt": "A 10-foot pole casts a 6-foot shadow. At the same time, a nearby tree casts a 21-foot shadow. What is the height of the tree, in feet?",
        "choices": {"A": "25", "B": "30", "C": "35", "D": "42"},
        "correct_answer": "C",
        "explanation": "The height-to-shadow ratio is constant. Since 10/6 = h/21, h = 35.",
        "solution_steps": ["Set up the similarity ratio: 10/6 = h/21.", "Multiply both sides by 21.", "h = 21 x 10 / 6.", "h = 35 feet."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_math",
        "topic": "Algebra",
        "skill": "Systems of equations",
        "difficulty": "medium",
        "prompt": "If 2x + y = 17 and x - y = 4, what is the value of x?",
        "choices": {"A": "5", "B": "6", "C": "7", "D": "9"},
        "correct_answer": "C",
        "explanation": "Add the equations to eliminate y: 3x = 21, so x = 7.",
        "solution_steps": ["Write the equations vertically.", "Add them: 2x + y + x - y = 17 + 4.", "Simplify to 3x = 21.", "Divide by 3: x = 7."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_math",
        "topic": "Advanced Math",
        "skill": "Exponential growth",
        "difficulty": "hard",
        "prompt": "A population doubles every 5 years. If the initial population is 1,200, which expression gives the population after t years?",
        "choices": {"A": "1200(2)^t", "B": "1200(2)^(t/5)", "C": "1200(5)^t", "D": "1200 + 2t"},
        "correct_answer": "B",
        "explanation": "A doubling happens every 5 years, so the number of doubling periods after t years is t/5.",
        "solution_steps": ["Start with the initial amount: 1200.", "The growth factor for each period is 2.", "The number of 5-year periods is t/5.", "Use 1200(2)^(t/5)."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_math",
        "topic": "Data Analysis",
        "skill": "Mean and total",
        "difficulty": "medium",
        "prompt": "The mean of 5 numbers is 18. If one number is removed, the mean of the remaining 4 numbers is 16. What number was removed?",
        "choices": {"A": "20", "B": "24", "C": "26", "D": "28"},
        "correct_answer": "C",
        "explanation": "The original total is 90. The new total is 64. The removed number is 90 - 64 = 26.",
        "solution_steps": ["Original total: 5 x 18 = 90.", "Remaining total: 4 x 16 = 64.", "Removed value = original total - remaining total.", "90 - 64 = 26."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_math",
        "topic": "Algebra",
        "skill": "Inequalities",
        "difficulty": "easy",
        "prompt": "Which inequality represents all values of x that are at least 3 units from 5 on the number line?",
        "choices": {"A": "|x - 5| >= 3", "B": "|x + 5| >= 3", "C": "|x - 3| <= 5", "D": "|x + 3| <= 5"},
        "correct_answer": "A",
        "explanation": "Distance from 5 is represented by |x - 5|. At least 3 means greater than or equal to 3.",
        "solution_steps": ["Distance from a number uses absolute value.", "Distance from 5 is |x - 5|.", "At least means >=.", "The inequality is |x - 5| >= 3."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_english",
        "topic": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "easy",
        "prompt": "The first prototype was easy to build. _____, it broke after only a few uses, so the team redesigned the frame.",
        "choices": {"A": "For example", "B": "However", "C": "Similarly", "D": "Therefore"},
        "correct_answer": "B",
        "explanation": "The second sentence contrasts the prototype being easy to build with it breaking quickly.",
        "solution_steps": ["Identify the first idea: easy to build.", "Identify the second idea: it broke quickly.", "The ideas contrast.", "Choose However."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_english",
        "topic": "Standard English Conventions",
        "skill": "Boundaries",
        "difficulty": "medium",
        "prompt": "Which choice completes the text correctly? The club planned the event carefully _____ attendance was higher than expected.",
        "choices": {"A": ", attendance", "B": "; attendance", "C": "attendance", "D": ", and attendance"},
        "correct_answer": "D",
        "explanation": "Two independent clauses can be joined with a comma and a coordinating conjunction such as and.",
        "solution_steps": ["Check the left side: it can stand alone.", "Check the right side: it can also stand alone.", "A comma alone would be a comma splice.", "Comma + and correctly joins the clauses."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_english",
        "topic": "Craft and Structure",
        "skill": "Text Structure and Purpose",
        "difficulty": "medium",
        "prompt": "A passage first describes a popular belief about study habits, then presents research that challenges that belief. What is the main purpose of the passage?",
        "choices": {"A": "To list unrelated study tips", "B": "To advertise a study product", "C": "To complicate a common assumption", "D": "To summarize a historical debate"},
        "correct_answer": "C",
        "explanation": "The structure moves from a belief to research that challenges it, so the passage complicates a common assumption.",
        "solution_steps": ["Track the passage movement.", "It starts with a popular belief.", "Then it gives research that challenges the belief.", "That purpose is to complicate an assumption."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_english",
        "topic": "Information and Ideas",
        "skill": "Inferences",
        "difficulty": "medium",
        "prompt": "Students who corrected their missed questions within 24 hours were less likely to repeat similar mistakes later. The finding suggests that _____.",
        "choices": {"A": "all mistakes disappear after one day", "B": "timely review can improve later performance", "C": "students should avoid difficult questions", "D": "review is useful only for math"},
        "correct_answer": "B",
        "explanation": "The finding connects quick correction with fewer repeated mistakes, so timely review can help later performance.",
        "solution_steps": ["Focus on the evidence given.", "Quick correction is linked to fewer repeated mistakes.", "Use cautious language.", "Timely review can improve later performance."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_english",
        "topic": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "hard",
        "prompt": "Notes: The app tracks daily reading. It shows a weekly graph. Students can set goals. Goal: emphasize how the app supports reflection. Which choice best accomplishes the goal?",
        "choices": {"A": "The app includes several screens and buttons.", "B": "Students can use the weekly graph to reflect on progress toward reading goals.", "C": "Daily reading can include fiction or nonfiction.", "D": "Many students use phones to organize schoolwork."},
        "correct_answer": "B",
        "explanation": "The goal is reflection, and the correct answer connects the graph to progress toward goals.",
        "solution_steps": ["Read the goal first: support reflection.", "Find notes related to reflection: graph and goals.", "Choose the answer that combines those notes.", "Choice B matches the goal directly."],
        "source_label": "expanded_seed",
    },
    {
        "domain": "sat_english",
        "topic": "Standard English Conventions",
        "skill": "Form, Structure, and Sense",
        "difficulty": "easy",
        "prompt": "Which choice completes the text correctly? Each of the science reports _____ a short summary of the results.",
        "choices": {"A": "include", "B": "includes", "C": "including", "D": "to include"},
        "correct_answer": "B",
        "explanation": "The subject Each is singular, so the singular verb includes is required.",
        "solution_steps": ["Find the true subject: Each.", "Ignore the nearby plural noun reports.", "Each is singular.", "Use includes."],
        "source_label": "expanded_seed",
    },
]

db = get_supabase_admin()
inserted = 0
for question in questions:
    existing = db.table("questions").select("id").eq("prompt", question["prompt"]).limit(1).execute().data
    if existing:
        continue
    db.table("questions").insert(question).execute()
    inserted += 1

print(f"inserted={inserted}")
